name: Cd-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Testing application
  ci:
    uses: ./.github/workflows/tests.yml

  # Building application
  build:
    needs: ci
    uses: ./.github/workflows/build.yml
  # Deploy application
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml