name: Cd-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Testing application
  tests:
    uses: ./.github/workflows/tests.yml

  # Building application
  build:
    uses: ./.github/workflows/build.yml
  # Deploy application
  deploy:
    uses: ./.github/workflows/deploy.yml