name: Cd-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Testing application
  tests:
    uses: ./tests.yml

  # Building application
  build:
    uses: ./build.yml
  # Deploy application
  deploy:
    needs: [ tests, build ]
    uses: ./deploy.yml