name: Cd-build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Testing application
  ci:
    uses: ./.github/workflows/children/tests.yml

  # Building application
  build:
    needs: ci
    uses: ./.github/workflows/children/build.yml
  # Deploy application
  deploy:
    needs: build
    uses: ./.github/workflows/children/deploy.yml