name: Cd-build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Testing application
  ci:
    uses: [./.github/workflows/tests.yml, ./.github/workflows/build.yml]
  # Deploy application
  deploy:
    needs: ci
    uses: ./.github/workflows/deploy.yml